"""
photos.py
─────────
Google Photos OAuth 2.0 integration.
Reads credentials from google_credentials.json; caches the token in google_token.json.
No files are uploaded — read-only access only.

Scopes used:
    https://www.googleapis.com/auth/photoslibrary.readonly
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import secrets
from pathlib import Path
from typing import Optional

import requests
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow

# ─── Config ───────────────────────────────────────────────────────────────────

CREDENTIALS_FILE = Path("google_credentials.json")
TOKEN_FILE = Path("google_token.json")

SCOPES = ["https://www.googleapis.com/auth/photoslibrary.readonly"]
REDIRECT_URI = "http://localhost:8000/auth/callback"

PHOTOS_API_BASE = "https://photoslibrary.googleapis.com/v1"

# Holds the PKCE verifier generated in get_auth_url() so exchange_code()
# can use it in the same server process without passing it through the browser.
_pkce_verifier: Optional[str] = None


# ─── Internal helpers ─────────────────────────────────────────────────────────

def _load_client_config() -> dict:
    """Read google_credentials.json and return its contents."""
    return json.loads(CREDENTIALS_FILE.read_text(encoding="utf-8"))


def _build_flow() -> Flow:
    return Flow.from_client_config(
        _load_client_config(),
        scopes=SCOPES,
        redirect_uri=REDIRECT_URI,
    )


# ─── Public functions ─────────────────────────────────────────────────────────

def get_auth_url() -> str:
    """
    Build and return the Google OAuth authorization URL with PKCE.
    Generates a fresh code_verifier each call and stores it module-level
    so exchange_code() can include it in the token request.
    """
    global _pkce_verifier

    # Generate a cryptographically random 64-char URL-safe verifier
    _pkce_verifier = secrets.token_urlsafe(64)

    # SHA-256 hash → base64url-encode (no padding) → code_challenge
    digest = hashlib.sha256(_pkce_verifier.encode("ascii")).digest()
    code_challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")

    flow = _build_flow()
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",               # force refresh_token every time
        code_challenge=code_challenge,
        code_challenge_method="S256",
    )
    return auth_url


def exchange_code(code: str) -> dict:
    """
    Exchange an authorization code (from the OAuth callback) for tokens.
    Includes the PKCE code_verifier generated by get_auth_url().
    Saves the token to google_token.json and returns the token dict.
    """
    flow = _build_flow()
    flow.fetch_token(code=code, code_verifier=_pkce_verifier)
    creds = flow.credentials

    token_data = {
        "token":         creds.token,
        "refresh_token": creds.refresh_token,
        "token_uri":     creds.token_uri,
        "client_id":     creds.client_id,
        "client_secret": creds.client_secret,
        "scopes":        list(creds.scopes or SCOPES),
    }
    TOKEN_FILE.write_text(json.dumps(token_data, indent=2), encoding="utf-8")
    return token_data


def get_credentials() -> Optional[Credentials]:
    """
    Load credentials from google_token.json.
    Refreshes the access token if it has expired.
    Returns None if the token file does not exist (user must authenticate first).
    """
    if not TOKEN_FILE.exists():
        return None

    data = json.loads(TOKEN_FILE.read_text(encoding="utf-8"))
    creds = Credentials(
        token=data.get("token"),
        refresh_token=data.get("refresh_token"),
        token_uri=data.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=data.get("client_id"),
        client_secret=data.get("client_secret"),
        scopes=data.get("scopes", SCOPES),
    )

    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        # Persist the refreshed access token
        data["token"] = creds.token
        TOKEN_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")

    return creds


def list_album_photos(album_id: str, credentials: Credentials) -> list[dict]:
    """
    Return all photos in the given Google Photos album.
    Handles pagination automatically.

    Each item dict contains:
        id, filename, mimeType, baseUrl, productUrl
    """
    results: list[dict] = []
    page_token: Optional[str] = None

    headers = {"Authorization": f"Bearer {credentials.token}"}

    while True:
        payload: dict = {"albumId": album_id, "pageSize": 100}
        if page_token:
            payload["pageToken"] = page_token

        try:
            response = requests.post(
                f"{PHOTOS_API_BASE}/mediaItems:search",
                headers=headers,
                json=payload,
                timeout=30,
            )
            response.raise_for_status()
        except requests.RequestException:
            return results

        body = response.json()
        for item in body.get("mediaItems", []):
            results.append({
                "id":         item.get("id"),
                "filename":   item.get("filename"),
                "mimeType":   item.get("mimeType"),
                "baseUrl":    item.get("baseUrl"),
                "productUrl": item.get("productUrl"),
            })

        page_token = body.get("nextPageToken")
        if not page_token:
            break

    return results


def get_photo_bytes(
    base_url: str,
    credentials: Credentials,
    width: int = 400,
) -> Optional[bytes]:
    """
    Download image bytes from a Google Photos baseUrl.

    width=400  → appends "=w400-h400" for a thumbnail
    width=0    → appends "=d" for the full-resolution original download
    """
    if width > 0:
        url = f"{base_url}=w{width}-h{width}"
    else:
        url = f"{base_url}=d"

    headers = {"Authorization": f"Bearer {credentials.token}"}
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        return response.content
    except requests.RequestException:
        return None
