"""
photos.py
─────────
Google Photos OAuth 2.0 integration.
Credentials are loaded from the GOOGLE_CREDENTIALS_JSON environment variable
(a JSON string) if set, otherwise falls back to google_credentials.json on disk.

Token lookup order (fastest → slowest):
  1. _token_cache  — in-memory, set after exchange_code() or a successful load
  2. GOOGLE_TOKEN_JSON env var — JSON string, useful for seeding an existing token
  3. google_token.json file — local development fallback

No files are uploaded — read-only access only.

Scopes used:
    https://www.googleapis.com/auth/photoslibrary.readonly
"""
from __future__ import annotations

import base64
import hashlib
import json
import os
import secrets
from pathlib import Path
from typing import Optional

import requests
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow

# ─── Config ───────────────────────────────────────────────────────────────────

TOKEN_FILE = Path("google_token.json")

SCOPES = ["https://www.googleapis.com/auth/photoslibrary.readonly"]

PHOTOS_API_BASE = "https://photoslibrary.googleapis.com/v1"

# Holds the PKCE verifier generated in get_auth_url() so exchange_code()
# can use it in the same server process without passing it through the browser.
_pkce_verifier: Optional[str] = None

# In-memory token cache — survives for the lifetime of the server process.
# Populated by exchange_code() and get_credentials() on first successful load.
_token_cache: Optional[dict] = None


# ─── Internal helpers ─────────────────────────────────────────────────────────

def _load_client_config() -> dict:
    """
    Load OAuth client config from the GOOGLE_CREDENTIALS_JSON env var (a JSON
    string) if set, otherwise read google_credentials.json from disk.
    Returns the full JSON including the "web" wrapper as Flow.from_client_config() expects.
    """
    creds_json = os.environ.get("GOOGLE_CREDENTIALS_JSON")
    if creds_json:
        return json.loads(creds_json)
    with open("google_credentials.json") as f:
        return json.load(f)


def _build_flow() -> Flow:
    redirect_uri = os.environ.get("REDIRECT_URI", "http://localhost:8000/auth/callback")
    return Flow.from_client_config(
        _load_client_config(),
        scopes=SCOPES,
        redirect_uri=redirect_uri,
    )


# ─── Public functions ─────────────────────────────────────────────────────────

def get_auth_url() -> str:
    """
    Build and return the Google OAuth authorization URL with PKCE.
    Generates a fresh code_verifier each call and stores it module-level
    so exchange_code() can include it in the token request.
    """
    global _pkce_verifier

    # Generate a cryptographically random 64-char URL-safe verifier
    _pkce_verifier = secrets.token_urlsafe(64)

    # SHA-256 hash → base64url-encode (no padding) → code_challenge
    digest = hashlib.sha256(_pkce_verifier.encode("ascii")).digest()
    code_challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")

    flow = _build_flow()
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",               # force refresh_token every time
        code_challenge=code_challenge,
        code_challenge_method="S256",
    )
    return auth_url


def exchange_code(code: str) -> dict:
    """
    Exchange an authorization code (from the OAuth callback) for tokens.
    Includes the PKCE code_verifier generated by get_auth_url().
    Stores the token in _token_cache and writes google_token.json (local dev).
    """
    global _token_cache

    flow = _build_flow()
    flow.fetch_token(code=code, code_verifier=_pkce_verifier)
    creds = flow.credentials

    token_data = {
        "token":         creds.token,
        "refresh_token": creds.refresh_token,
        "token_uri":     creds.token_uri,
        "client_id":     creds.client_id,
        "client_secret": creds.client_secret,
        "scopes":        list(creds.scopes or SCOPES),
    }

    # Always keep in memory
    _token_cache = token_data

    # Local dev fallback — write to disk (ignored on Railway after redeploy)
    try:
        TOKEN_FILE.write_text(json.dumps(token_data, indent=2), encoding="utf-8")
    except OSError:
        pass

    return token_data


def _load_token_data() -> Optional[dict]:
    """
    Load raw token data using the priority chain:
      1. _token_cache (in-memory)
      2. GOOGLE_TOKEN_JSON env var
      3. google_token.json file
    Returns None if none of the sources has a token.
    """
    global _token_cache

    if _token_cache:
        return _token_cache

    env_token = os.environ.get("GOOGLE_TOKEN_JSON")
    if env_token:
        _token_cache = json.loads(env_token)
        return _token_cache

    if TOKEN_FILE.exists():
        _token_cache = json.loads(TOKEN_FILE.read_text(encoding="utf-8"))
        return _token_cache

    return None


def get_credentials() -> Optional[Credentials]:
    """
    Return valid Google credentials using the three-source priority chain.
    Refreshes the access token if expired and updates _token_cache.
    Returns None if no token is found (user must authenticate first).
    """
    global _token_cache

    data = _load_token_data()
    if data is None:
        return None

    creds = Credentials(
        token=data.get("token"),
        refresh_token=data.get("refresh_token"),
        token_uri=data.get("token_uri", "https://oauth2.googleapis.com/token"),
        client_id=data.get("client_id"),
        client_secret=data.get("client_secret"),
        scopes=data.get("scopes", SCOPES),
    )

    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
        data["token"] = creds.token
        _token_cache = data
        # Best-effort disk write for local dev
        try:
            TOKEN_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except OSError:
            pass

    return creds


def list_album_photos(album_id: str, credentials: Credentials) -> list[dict]:
    """
    Return all photos in the given Google Photos album.
    Handles pagination automatically.

    Each item dict contains:
        id, filename, mimeType, baseUrl, productUrl
    """
    results: list[dict] = []
    page_token: Optional[str] = None

    headers = {"Authorization": f"Bearer {credentials.token}"}

    while True:
        payload: dict = {"albumId": album_id, "pageSize": 100}
        if page_token:
            payload["pageToken"] = page_token

        try:
            response = requests.post(
                f"{PHOTOS_API_BASE}/mediaItems:search",
                headers=headers,
                json=payload,
                timeout=30,
            )
            response.raise_for_status()
        except requests.RequestException:
            return results

        body = response.json()
        for item in body.get("mediaItems", []):
            results.append({
                "id":         item.get("id"),
                "filename":   item.get("filename"),
                "mimeType":   item.get("mimeType"),
                "baseUrl":    item.get("baseUrl"),
                "productUrl": item.get("productUrl"),
            })

        page_token = body.get("nextPageToken")
        if not page_token:
            break

    return results


def get_photo_bytes(
    base_url: str,
    credentials: Credentials,
    width: int = 400,
) -> Optional[bytes]:
    """
    Download image bytes from a Google Photos baseUrl.

    width=400  → appends "=w400-h400" for a thumbnail
    width=0    → appends "=d" for the full-resolution original download
    """
    if width > 0:
        url = f"{base_url}=w{width}-h{width}"
    else:
        url = f"{base_url}=d"

    headers = {"Authorization": f"Bearer {credentials.token}"}
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        return response.content
    except requests.RequestException:
        return None
